name: Android Build
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK Manager
      run: |
        # Installer les composants nécessaires
        export ANDROID_HOME=$GITHUB_WORKSPACE/android-sdk
        mkdir -p $ANDROID_HOME/cmdline-tools
        
        # Télécharger et installer Command line tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        
        # Ajouter au PATH et exporter la variable d'environnement
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV
    
    - name: Install Android SDK components
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.3.6528147"
    
    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "ndk.dir=$ANDROID_HOME/ndk/21.3.6528147" >> local.properties
        cat local.properties
    
    - name: Download OpenCV SDK
      run: |
        wget https://sourceforge.net/projects/opencvlibrary/files/4.1.0/opencv-4.1.0-android-sdk.zip
        unzip -q opencv-4.1.0-android-sdk.zip
        mkdir -p OpenCV
        cp -r OpenCV-android-sdk/sdk OpenCV/
    
    - name: Update settings.gradle
      run: |
        echo "include ':app', ':OpenCV'" > settings.gradle
        echo "project(':OpenCV').projectDir = new File('OpenCV/sdk')" >> settings.gradle
    
    - name: Download YOLO weights
      run: |
        mkdir -p app/src/main/assets
        wget https://pjreddie.com/media/files/yolov3-tiny.weights -O app/src/main/assets/yolov3-tiny.weights
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Display environment info
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        ls -la $ANDROID_HOME
        echo "Java version:"
        java -version
    
    - name: Build with Gradle
      run: ./gradlew assembleDebug --info
    
    - name: List build outputs
      run: |
        find app/build -name "*.apk"
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 5
        if-no-files-found: warn
