name: Android Build
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11  # Mise à jour vers Java 11
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Install NDK
      run: |
        echo "y" | sdkmanager --install "ndk;21.3.6528147"
    
    - name: Create local.properties with correct paths
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "ndk.dir=$ANDROID_HOME/ndk/21.3.6528147" >> local.properties
        cat local.properties
    
    - name: Download OpenCV SDK
      run: |
        wget https://sourceforge.net/projects/opencvlibrary/files/4.1.0/opencv-4.1.0-android-sdk.zip
        unzip opencv-4.1.0-android-sdk.zip
        mkdir -p OpenCV
        cp -r OpenCV-android-sdk/sdk OpenCV/
    
    - name: Update settings.gradle
      run: |
        echo "include ':app', ':OpenCV'" > settings.gradle
        echo "project(':OpenCV').projectDir = new File('OpenCV/sdk')" >> settings.gradle
    
    - name: Download YOLO weights
      run: |
        mkdir -p app/src/main/assets
        wget https://pjreddie.com/media/files/yolov3-tiny.weights -O app/src/main/assets/yolov3-tiny.weights
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Display environment info
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        ls -la $ANDROID_HOME
    
    - name: Build with Gradle
      run: ./gradlew assembleDebug --info
    
    - name: List APK file
      run: ls -la app/build/outputs/apk/debug/ || echo "No APK found"
    
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
      if: success()
